
services:
  graphdb:
    image: ontotext/graphdb:10.8.4
    container_name: graphdb
    ports:
      - "7200:7200"
    environment:
      - GRAPHDB_HOME=/opt/graphdb/home
      - GRAPHDB_MIN_DISK_SPACE_MB=50
      - JAVA_OPTS=-Dgraphdb.workbench.maxUploadSize=5000000

    volumes:
      - graphdb-data:/opt/graphdb/home
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/webproj
    working_dir: /webproj
    ports:
      - "8000:8000"
    depends_on:
      - graphdb


volumes:
  graphdb-data:
