version: '3.8'

services:
  graphdb:
    image: ontotext/graphdb:10.8.4
    container_name: graphdb
    ports:
      - "7200:7200"
    environment:
      - GRAPHDB_HOME=/opt/graphdb/home
    volumes:
      - graphdb-data:/opt/graphdb/home
    restart: unless-stopped

  web:
    build: ./app
    container_name: django_app
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - graphdb

volumes:
  graphdb-data:
